matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        chrome: stable
      language: android
      android:
        components:
          - build-tools-28.0.3
          - android-28
      env: MP_TARGET=COMMON
      install: true
      script: ./gradlew reaktive:check reaktive-test:check rxjava2-interop:check -DMP_TARGET=$MP_TARGET
    - os: osx
      osx_image: xcode10.2
      language: java
      env: MP_TARGET=IOS
      install: true
      script: ./gradlew reaktive:check reaktive-test:check -DMP_TARGET=$MP_TARGET
    - os: linux
      language: android
      android:
        components:
          - build-tools-28.0.3
          - android-28
      env: MP_TARGET=META
      install: true
      script: true
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew bintrayUpload -DMP_TARGET=$MP_TARGET -Pbintray_user=$BINTRAY_USER -Pbintray_key=$BINTRAY_KEY
  on:
    tags: true
